name: Update data
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: "0 */12 * * *" 
jobs:
  build: 
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: Update apt
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - name: Install library and other requirements
      run: |
        pip install -r requirements.txt 
    - name: Fetch and Build html page
      env:
        GH_TOKEN:  ${{ secrets.GH_TOKEN }}
      run: |
        ./fetch.sh
        python3 ./generate_page.py
    - name: Commit changes
      env:
        GH_MAIL: your-email@example.com
        GH_USER: your-github-username
      run: |
        git config --global user.email $GH_MAIL
        git config --global user.name $GH_USER
        diff_count=$(echo `git status -s | wc -l`)
        if [ $diff_count -gt 0 ]; then
          echo "There are some changes."
            git add index.html
            git commit -m "Updated index.html"
          git push origin main
        else
          echo "No change."
        fi
